{{- $name := include "tt-profile.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "tt-profile.name" . }}
    chart: {{ template "tt-profile.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  CosmosDb__Key: {{ .Values.inf.db.profile.auth }}
  CosmosDb__Host: {{ .Values.inf.db.profile.host }}
  ApplicationInsights__InstrumentationKey:  "{{ .Values.inf.appinsights.id }}"
  ProfilesImageUrl: {{ .Values.inf.storage.profileimages }}
  ISSUER: {{ .Values.sec.issuer }}
  SECURITYKEY: {{ .Values.sec.securityKey }}
