version: "3.4"

services:
  cart.api:
    image: ${REGISTRY:-tailwindtraders}/cart.api:${TAG:-latest}
    build:
      context: Services/Tailwind.Traders.Cart.Api
      dockerfile: Dockerfile

  product.api:
    image: ${REGISTRY:-tailwindtraders}/product.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Tailwind.Traders.Product.Api/Dockerfile

  profile.api:
    image: ${REGISTRY:-tailwindtraders}/profile.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Tailwind.Traders.Profile.Api/Dockerfile

  login.api:
    image: ${REGISTRY:-tailwindtraders}/login.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Tailwind.Traders.Login.Api/Dockerfile

  coupon.api:
    image: ${REGISTRY:-tailwindtraders}/coupon.api:${TAG:-latest}
    container_name: coupon-node
    build:
      context: Services/Tailwind.Traders.Coupon.Api
      dockerfile: Dockerfile

  popular-product.api:
    image: ${REGISTRY:-tailwindtraders}/popular-product.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Tailwind.Traders.PopularProduct.Api/Dockerfile

  stock.api:
    image: ${REGISTRY:-tailwindtraders}/stock.api:${TAG:-latest}
    container_name: stock-java
    build:
      context: ./Services/Tailwind.Traders.Stock.Api/
      dockerfile: Dockerfile

  image-classifier.api:
    image: ${REGISTRY:-tailwindtraders}/image-classifier.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Tailwind.Traders.ImageClassifier.Api/Dockerfile

  mobileapigw:
    image: ${REGISTRY:-tailwindtraders}/mobileapigw:${TAG:-latest}
    build:
      context: .
      dockerfile: ApiGWs/Tailwind.Traders.Bff/Dockerfile

  webapigw:
    image: ${REGISTRY:-tailwindtraders}/webapigw:${TAG:-latest}
    build:
      context: .
      dockerfile: ApiGWs/Tailwind.Traders.WebBff/Dockerfile
    depends_on:
      - product.api
      - profile.api
      - login.api
      - coupon.api
      - popular-product.api
      - stock.api
      - image-classifier.api
