version: "3.4"

services:
  product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CosmosDb__Host=${COSMOSDB_HOST:-https://10.0.75.1:8081} # Emulator URI
      - CosmosDb__Key=${COSMOSDB_AUTHKEY:-C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==} # Emulator Key
      - ProductImagesUrl=
      - ProductDetailImagesUrl=
      - ApplicationInsights__InstrumentationKey=
    ports:
      - "5000:80"

  profile.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CosmosDb__Host=${COSMOSDB_HOST:-https://10.0.75.1:8081} # Emulator URI
      - CosmosDb__Key=${COSMOSDB_AUTHKEY:-C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==} # Emulator Key
      - ProfilesImageUrl=
      - SecurityKey=nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
      - Issuer=TTFakeLogin
      - ApplicationInsights__InstrumentationKey=
    ports:
      - "5001:80"

  login.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ProfilesImageUrl=
      - SecurityKey=nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
      - Issuer=TTFakeLogin
      - ApplicationInsights__InstrumentationKey=
    ports:
      - "5008:80"

  coupon.api:
    environment:
      - CONNECTIONSTRING= # Connect to CosmosDb
      - PORT=3000
      - COUPON_COLLECTION=CouponCollection
      - URL_BASE= # Connect to CosmosDb ?
      - ISSUER=TTFakeLogin
      - SECURITYKEY=nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
      - APPLICATIONINSIGHTSIK=
    ports:
      - "5002:3000"

  popular-product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Issuer=TTFakeLogin
      - SecurityKey=nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
      - AzureStorageUrl=
      - ApplicationInsightsIK=
    ports:
      - "5003:80"

  stock.api:
    environment:
      - COSMOSDB_HOST=${COSMOSDB_HOST:-https://10.0.75.1:8081} # Emulator URI
      - COSMOSDB_AUTHKEY=${COSMOSDB_AUTHKEY:-C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==} # Emulator Key
      - Issuer=TTFakeLogin
      - SecurityKey=nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
      - APPLICATION_INSIGHTS_IKEY=
    ports:
      - "5004:8080"

  image-classifier.api:
    environment:
      - ImagePath=/imguploads
      - ISSUER=TTFakeLogin
      - SECURITYKEY=nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
      - ApplicationInsights__InstrumentationKey=
    ports:
      - "5006:80"

  cart.api:
    environment:
      - HOST=${COSMOSDB_HOST:-https://10.0.75.1:8081} # Emulator URI
      - AUTHKEY=${COSMOSDB_AUTHKEY:-C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==} # Emulator Key
      - ISSUER=TTFakeLogin
      - SECURITYKEY=nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
      - UseB2C=${UseB2C:-false}
      - APPLICATIONINSIGHTSIK=
    ports:
      - "5007:3001"

  mobileapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PopularProductsApiUrl=http://popular-product.api
      - ProductsApiUrl=http://product.api
      - ProfileApiUrl=http://profile.api
      - CouponsApiUrl=http://coupon.api
      - ImageClassifierApiUrl=http://image-classifier.api
      - LoginApiUrl=http://login.api
      - RegisterUsers=${RegisterUsers:-false}
      - RegistrationUsersEndpoint=
    ports:
      - "5100:80"

  webapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PopularProductsApiUrl=http://popular-product.api
      - ProductsApiUrl=http://product.api
      - ProfileApiUrl=http://profile.api
      - LoginApiUrl=http://login.api
      - CouponsApiUrl=http://coupon.api:3000
      - ImageClassifierApiUrl=http://image-classifier.api
      - StockApiUrl=http://stock.api:8080
      - SECURITYKEY=nEpLzQJGNSCNL5H6DIQCtTdNxf5VgAGcBbtXLms1YDD01KJBAs0WVawaEjn97uwB
      - ISSUER=TTFakeLogin
      - UseMlNetClassifier=true
      - UseB2C=${UseB2C:-false}
      - B2CIssuer=
      - Authority=
      - ApplicationInsights__InstrumentationKey=
      - RegisterUsers=${RegisterUsers:-false}
      - RegistrationUsersEndpoint=http://localhost:51402/UserService.svc
    ports:
      - "5200:80"
