{{- $name := include "tt-stock.fullname" . -}}


apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "tt-stock.name" . }}
    chart: {{ template "tt-stock.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  APPLICATION_INSIGHTS_IKEY:  "{{ .Values.inf.appinsights.id }}"
  COSMOSDB_AUTHKEY: {{ .Values.inf.db.stock.auth }}
  COSMOSDB_HOST: {{ .Values.inf.db.stock.host }}
  ISSUER: {{ .Values.sec.issuer }}
  SECURITYKEY: {{ .Values.sec.securityKey }}
  CLOUD_PLATFORM: "{{ .Values.inf.cloudPlatform }}"
  stockItemTableName: {{ .Values.inf.db.stock.stockItemTable }}
  region: {{ .Values.inf.awsRegion }}
  projectId: {{ .Values.inf.db.stock.projectId }}
  private_key_id: {{ .Values.inf.db.stock.privateKeyId }}
  private_key: {{ .Values.inf.db.stock.privateKey }}
  client_email: {{ .Values.inf.db.stock.clientEmail }}
  client_id: {{ .Values.inf.db.stock.clientId }}
  token_uri: {{ .Values.inf.db.stock.tokenUri }}