name: Deploy in a containerized App Service

on:
  push:
    branches:
      - main
    paths:
      - 'TailwindTraders.Website/**'
      - '.github/workflows/container_appservice.yaml'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker build and push
      working-directory: TailwindTraders.Website/Source/Tailwind.Traders.Web
      run: |
        docker build . --build-arg sdkTag=5.0 --build-arg runtimeTag=5.0 -t tailwindtraders/web:gh-${{ github.sha }} -t latest
        docker push tailwindtraders/web:gh-${{ github.sha }}

    - uses: azure/appservice-settings@v1
      with:
         app-name: ${{ secrets.CONTAINER_APPSERVICE_NAME }}
         app-settings-json: '${{ secrets.CONTAINER_APP_SETTINGS }}'

    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.CONTAINER_APPSERVICE_NAME }}
        images: 'tailwindtraders/web:gh-${{ github.sha }}'
