name: Build check on PR

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'TailwindTraders.Website/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Docker build
      working-directory: TailwindTraders.Website/Source/Tailwind.Traders.Web
      run: |
        docker build . --build-arg sdkTag=5.0 --build-arg runtimeTag=5.0 -t tailwindtraders/web:gh-${{ github.sha }} -t latest
