name: Deploy telephony bot

on:
  push:
    branches:
      - main
    paths:
      - 'TailwindTradersLogicApp/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}


    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.15.0
    
    - name: 'npm install, build, and test'
      run: |
        npm install
        node provisionComposer.js --subscriptionId=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }} --name=Bot --appPassword=${{ secrets.BOT_APP_PASSWORD }} --environment=prod --appId=${{ secrets.BOT_APP_ID }} --tenantId=${{ secrets.BOT_TENANT_ID }}
      working-directory:  TailwindTradersBotComposer/scripts

    - name: Azure logout
      run: |
        az logout
