name: TailwindTraders Website Pipelines
on:
  push:
    branches: [main, ]
    paths:
      - 'TailwindTraders.Website/**'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  pr-build:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Docker build
      working-directory: TailwindTraders.Website/Source/Tailwind.Traders.Web
      run: |
        docker build . --build-arg sdkTag=5.0 --build-arg runtimeTag=5.0 -t tailwindtraders/web:gh-${{ github.sha }} -t latest

  main-build:
    if: ${{ github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Docker build
      working-directory: TailwindTraders.Website/Source/Tailwind.Traders.Web
      run: |
        docker build . --build-arg sdkTag=5.0 --build-arg runtimeTag=5.0 -t tailwindtraders/web:gh-${{ github.sha }} -t latest

  nightly-build-and-deploy:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_2 }}

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker build and push
      working-directory: TailwindTraders.Website/Source/Tailwind.Traders.Web
      run: |
        docker build . --build-arg sdkTag=5.0 --build-arg runtimeTag=5.0 -t tailwindtraders/web:gh-${{ github.sha }} -t latest
        docker push tailwindtraders/web:gh-${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.CONTAINER_APPSERVICE_NAME }}
        images: 'tailwindtraders/web:gh-${{ github.sha }}'