apiVersion: v1
kind: Service
metadata:
  name: rewards-registration
  labels:
    app: {{ template "tt-rewards-registration.name" . }}
    chart: {{ template "tt-rewards-registration.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "tt-rewards-registration.name" . }}
    release: {{ .Release.Name }}