replicaCount: 1
applicationName: tailwindtraders

image:
  repository: tailwindtradersacr.azurecr.io/profile.api
  tag: prod
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
  requests:
    cpu: "100m"

nodeSelector:
  "kubernetes.io/os": linux

tolerations: []

affinity: {}

env:
  configmap:
    - name: ApplicationInsights__InstrumentationKey
    - name: CosmosDb__Host
    - name: CosmosDb__Key
    - name: ProfilesImageUrl
    - name: ISSUER
    - name: SECURITYKEY
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
