replicaCount: 1
applicationName: tailwindtraders

image:
  repository: tailwindtradersacr.azurecr.io/stock.api
  tag: prod
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
  requests:
    cpu: "100m"

nodeSelector:
  "kubernetes.io/os": linux

tolerations: []

affinity: {}

env:
  configmap:
    - name: APPLICATION_INSIGHTS_IKEY
    - name: ISSUER
    - name: SECURITYKEY
    - name: COSMOSDB_AUTHKEY
    - name: COSMOSDB_HOST
    - name: CLOUD_PLATFORM
    - name: stockItemTableName
    - name: region
    - name: projectId
    - name: private_key_id
    - name: private_key
    - name: client_email
    - name: client_id
    - name: token_uri
  values: {}

probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 100
    periodSeconds: 30
    port: http
