replicaCount: 1
applicationName: tailwindtraders

image:
  repository: tailwindtradersacr.azurecr.io/popular-product.api
  tag: prod
  pullPolicy: Always

initImage:
  repository: tailwindtradersacr.azurecr.io/popular-product-seed.api
  tag: prod
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
  requests:
    cpu: "100m"

nodeSelector:
  "kubernetes.io/os": linux

tolerations: []

affinity: {}

env:
  configmap:
    - name: ApplicationInsightsIK
    - name: AUTHKEY
    - name: HOST
    - name: AzureStorageUrl
    - name: ISSUER
    - name: SECURITYKEY
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development

probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 20
    periodSeconds: 30
    port: http
