apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: products-reqs-progress-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tailwindtraders-product
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Pods
    pods:
      metricName: http_requests_in_progress
      targetAverageValue: 3