{{- $name := include "tt-cart.fullname" . -}}


apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "tt-cart.name" . }}
    chart: {{ template "tt-cart.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  AUTHKEY: {{ .Values.inf.db.cart.auth }}
  HOST: {{ .Values.inf.db.cart.host }}
  ISSUER: {{ .Values.sec.issuer }}
  SECURITYKEY: {{ .Values.sec.securityKey }}
  UseB2C: {{ .Values.B2C.UseB2C | quote }}
  tenantID: {{ .Values.B2C.tenantID | quote }}
  clientID: {{ .Values.B2C.clientID | quote }}
  policyName: {{ .Values.B2C.policyName | quote }}
  identityMetadata: {{ .Values.B2C.identityMetadata | quote }}
  issuer: {{ .Values.B2C.issuer | quote }}
  APPLICATIONINSIGHTSIK:  "{{ .Values.inf.appinsights.id }}"
  CLOUD_PLATFORM: "{{ .Values.inf.cloudPlatform }}"


