{{- $name := include "tt-products.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "tt-products.name" . }}
    chart: {{ template "tt-products.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  CosmosDb__Key: {{ .Values.inf.db.products.auth }}
  CosmosDb__Host: {{ .Values.inf.db.products.host }}

  AWS_PRODUCT_PRODUCTITEM_TABLE: {{ .Values.inf.db.products.productItemTable }}
  AWS_PRODUCT_BRAND_TABLE: {{ .Values.inf.db.products.brandTable }}
  AWS_PRODUCT_FEATURE_TABLE: {{ .Values.inf.db.products.featureTable }}
  AWS_PRODUCT_TAG_TABLE: {{ .Values.inf.db.products.tagTable }}
  AWS_PRODUCT_TYPE_TABLE: {{ .Values.inf.db.products.typeTable }}
  AWS_REGION: {{ .Values.inf.awsRegion }}

  ProductImagesUrl: {{ .Values.inf.storage.productimages }}
  ProductDetailImagesUrl: {{ .Values.inf.storage.productdetailimages }}
  ApplicationInsights__InstrumentationKey:  "{{ .Values.inf.appinsights.id }}"  
  ISSUER: {{ .Values.sec.issuer }}
  SECURITYKEY: {{ .Values.sec.securityKey }}
  CLOUD_PLATFORM: "{{ .Values.inf.cloudPlatform }}"
