{{- $name := include "tt-products.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "tt-products.name" . }}
    chart: {{ template "tt-products.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  CosmosDb__Key: {{ .Values.inf.db.products.auth }}
  CosmosDb__Host: {{ .Values.inf.db.products.host }}
  ProductImagesUrl: {{ .Values.inf.storage.productimages }}
  ProductDetailImagesUrl: {{ .Values.inf.storage.productdetailimages }}
  ApplicationInsights__InstrumentationKey:  "{{ .Values.inf.appinsights.id }}"  
  ISSUER: {{ .Values.sec.issuer }}
  SECURITYKEY: {{ .Values.sec.securityKey }}
  CLOUD_PLATFORM: "{{ .Values.inf.cloudPlatform }}"
