replicaCount: 1
applicationName: tailwindtraders

image:
  repository: tailwindtradersacr.azurecr.io/cart.api
  tag: prod
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
  requests:
    cpu: "100m"

nodeSelector:
  "kubernetes.io/os": linux

tolerations: []

affinity: {}

env:
  configmap:
    - name: ApplicationInsights__InstrumentationKey
    - name: ConnectionString
    - name: ProfilesImageUrl
    - name: SecurityKey
    - name: Issuer
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development

probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 20
    periodSeconds: 30
    port: 80
